<?php
    $frontController = Zend_Controller_Front::getInstance();
    $request = $frontController->getRequest();
    $authSession = TechTree_Session::getNamespace('Auth');
    $userId = $authSession->techsId;
    $userSettings = new Application_Model_UserSettings();
    $planetTechs = $userSettings->getPlanetTechs($userId, 'Forschungen');
    $this->headTitle('Forschungen');
?>
        <div class="ttCategory">
            <div class="ttCategoryTitle">Forschungen</div>
            <form action="<?php echo $this->url(array(
                'controller' => $request->getParam('controller'),
                'action' => $request->getParam('action'),
            ), null, true); ?>" method="post" id="category-changer"><select name="category" onChange="document.getElementById('category-changer').submit();">
                    <option class="italic" value="">-- Kategorieauswahl --</option>
<?php
    foreach($this->typeCategories as $typeCategory)
    {
?>
                    <option value="<?php echo $typeCategory['name']; ?>"<?php echo ($request->getParam('category') === $typeCategory['name']) ? ' selected="selected"' : ''; ?>><?php echo $typeCategory['dname']; ?></option>
<?php
    }
?>
                </select></form>
<?php
    foreach($this->typeItems as $itemCategory => $categoryItems)
    {
?>
            <div class="subCategory">
                <div class="subCategoryTitle"><?php echo $itemCategory; ?></div>
<?php
        $index = 0;
        foreach($categoryItems as $categoryItem)
        {
            $planetTechExists = false;
            $maxLevelReached = false;
            if(isset($planetTechs[$categoryItem['name']]))
            {
                $planetTechExists = true;
                if($planetTechs[$categoryItem['name']]['level'] == $categoryItem['max_level'])
                {
                    $maxLevelReached = true;
                }
            }
            $index++;
            if(($index % 2) == 1)
            {
                $styleSuffix = 'Dark';
            }
            else
            {
                $styleSuffix = '';
            }
?>
                <div class="subCategoryItem<?php echo $styleSuffix; ?> h16">
                    <div class="float-left align-left">
                        <?php echo $this->hyperlink($categoryItem['dname'], array(
                        'controller' => 'objects',
                        'action' => 'details',
                        'id' => $categoryItem['name'],
                ));?> (<?php echo $categoryItem['name']; ?>)
                    </div>
                    <div class="level-info<?php echo $maxLevelReached ? ' bold' : ''; ?>"><?php echo $planetTechExists ? $planetTechs[$categoryItem['name']]['level'] : '0'; ?> / <?php echo $categoryItem['max_level']; ?></div>
                </div>
<?php
        }
?>
            </div>
<?php
    }
?>
        </div>
