<div class="ttCategory">
    <div class="ttCategoryTitle">Postfach</div>
<?php
foreach ($this->messages as $messageId => $message) {
?>
    <div class="subCategory">
        <div class="messageTable">
            <div class="message">
                <div class="from"><?php echo $message['from']; ?></div>
                <div class="subject"><?php echo $this->escape($message['subject']); ?></div>
                <div class="date"><?php echo date('d.m.Y H:i:s', $message['time']); ?></div>
                <div class="status<?php echo $message['new'] ? ' new' : ''; ?>"></div>
                <div class="clear"></div>
            </div>
            <div class="clear"></div>
            <div id="loader<?php echo $messageId; ?>" class="ajax-loader"></div>
            <div class="msgContent" id="msg<?php echo $messageId; ?>">
                <div class="msgBody dark"></div>
                <div class="actions">
                    <div class="toolbutton action reply">Antworten</div>&nbsp;
                    <div class="toolbutton action delete">Löschen</div>
                    <div class="clear"></div>
                </div>
                <form action="<?php echo $this->url(array('controller' => 'message', 'action' => 'ajax-send-reply')); ?>" onsubmit="return false;" id="frm-<?php echo $messageId; ?>">
                    <div class="msgReply">
                        <input type="hidden" name="id" value="<?php echo $messageId; ?>" />
                        <div class="label"><label for="reply-subject-<?php echo $messageId; ?>">Betreff:</label></div>
                        <div class="input"><input type="text" name="subject" id="reply-subject-<?php echo $messageId; ?>" value="Re: <?php echo str_replace('Re: ', '', $message['subject']); ?>" /></div>
                        <div class="clear"></div>
                        <div class="label"><label for="reply-message-<?php echo $messageId; ?>">Nachricht:</label></div>
                        <div class="input"><textarea name="message" id="reply-message-<?php echo $messageId; ?>" cols="50" rows="10"></textarea></div>
                        <div class="clear"></div>
                        <div class="label"></div>
                        <div class="input"><input type="submit" value="Absenden" onclick="sendReply('<?php echo $messageId; ?>');" /></div>
                        <div class="clear"></div>
                    </div>
                </form>
                <div class="clear"></div>
            </div>
        </div>
        <div class="clear"></div>
    </div>
<?php
}
?>
</div>
<script type="text/javascript">
<?php
$this->jQuery()->onLoadCaptureStart();
?>
$('.message').toggle(function() {
    var msgContent = $(this).parent().children('.msgContent');
    var msgId = msgContent.attr('id').substring(3);
    $('#loader' + msgId).slideDown(100);
    var msgBody = msgContent.find('.msgBody');
    msgBody.load('<?php echo $this->url(array('controller' => 'message', 'action' => 'ajax-get-message')); ?>/id/' + msgId + '/', function(data) {
        var msgStatus = $(msgContent).parent().children('.message').children('.status');
        if (msgStatus.hasClass('new')) {
            msgStatus.removeClass('new');
            $('#newMsgs').html($('#newMsgs').html() - 1);
        }
        $(msgContent).children('form').children('.msgReply').children('.input').children('textarea').val(data.replace(/^(.)/g, '\n\$RE\$\n$1').replace(/\n$/, '').replace(/\n/g, '\n> ').replace('> $RE$', ''));
        msgBody.html(data.replace(/\n/g,'<br/>\n'));
        $('#loader' + msgId).slideUp(100);
        msgContent.slideDown(250);
    });
}, function() {
    var msgContent = $(this).parent().children('.msgContent');
    msgContent.slideUp(250);
});
$('.action.reply').toggle(function() {
    $(this).parent().parent().children('form').children('.msgReply').slideDown(250);
}, function() {
    $(this).parent().parent().children('form').children('.msgReply').slideUp(250);
});
$('.action.delete').bind('click', function() {
    var msgContent = $(this).parent().parent();
    var msgTable = msgContent.parent();
    var isNew = msgTable.children('.message').children('status').hasClass('new');
    var msgDiv = msgTable.parent();
    var msgId = msgContent.attr('id').substring(3);
    var baseUrl = '<?php echo $this->url(array('controller' => 'message', 'action' => 'ajax-delete-message')); ?>';
    $('<div>Soll die Nachricht wirklich gelöscht werden?<\/div>').dialog({
        'buttons': [ {
            'text': "Ja",
            'click': function() {
                msgDiv.slideUp(250, function() {
                    $.ajax(baseUrl + '/id/' + msgId);
                    $('#totalMsgs').html($('#totalMsgs').html() - 1);
                    if (isNew) {
                        $('#newMsgs').html($('#newMsgs').html() - 1);
                    }
                });
                $(this).dialog('close');
            }
        }, {
            'text': "Nein",
            'click': function() {
                $(this).dialog('close');
            }
        } ],
        'title':'Nachricht löschen',
        'closeOnEscape':false,
        'modal':true
    });
});
<?php
$this->jQuery()->onLoadCaptureEnd();
$this->jQuery()->javascriptCaptureStart();
?>
function sendReply(msgId)
{
    var form = $('#frm-' + msgId);
    var formData = form.serializeArray();
    $.ajax({
        type:'POST',
        url:form.attr('action'),
        data:formData,
        success: function(data) {
            var msg = 'Die Nachricht konnte nicht gesendet werden.\n\nFehlermeldung: %s';
            if (data == true) {
                msg = 'Die Nachricht wurde verschickt.';
            } else {
                msg = msg.replace('%s', data);
            }
            $('<div>' + msg.replace(/\n/g, '<br\/>\n') + '<\/div>').dialog({
                modal:true,
                buttons:{
                    'OK':function() { $(this).dialog('close'); }
                }
            });
            form.children('.msgReply').slideUp(250);
        }
    });
}
<?php
$this->jQuery()->javascriptCaptureEnd();
?>
</script>